[postgres]
database_host = postgres
database_name = airflow_reddit
database_port = 5432
database_username = postgres
database_password = postgres


[redshift]
database_host = reddit-workgroup.389405924210.us-east-1.redshift-serverless.amazonaws.com
database_name = dev
database_port = 5439
database_username = admin
database_password =


[file_paths]
input_path = /opt/airflow/data/input
output_path = /opt/airflow/data/output


[aws]
aws_access_key_id = AKIAVVKTG3NZCM4CXA4H
aws_secret_access_key = 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
aws_region = us-east-1
aws_bucket_name = reddit-data-engineering-giftson-us-east-1